package bslsjdk.mcjavanpu;

import net.fabricmc.loader.api.FabricLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Runtime switches, stored in config/mcjavanpu.properties.
 *
 *  enabled    - master switch (the in-game screen toggles this too)
 *  autoWarmup - build + calibrate the graphs in the background at world load,
 *               so the very first real use is not the slow path
 *  debugLog   - log every call instead of only summaries
 *  autoProbe  - run the full diagnostic set unattended at game start and keep a
 *               rolling heartbeat. Results go to logs/mcjavanpu-npu.log. This is
 *               what makes the mod measurable without typing a command.
 *  guardEnabled - adaptive backoff. Watches the p99 cost of real calls and
 *               temporarily disables the NPU when it stops being worth it, then
 *               re-arms on its own. Protects the frame rate rather than the
 *               benchmark number.
 *  lightBatch - how many 8x8x8 blocks go into one propagation batch (legacy)
 *  lightMode - how light maths runs:
 *                 VANILLA - hands off, the game does exactly what it always did
 *                 NPU     - the NPU owns the propagation, the game's queues are skipped
 *                 ASSIST  - the NPU warms the field up, the game still finishes it
 *  chunkMode - same three-way choice for chunk work (noise, section fill)
 *  lightFoldRadius - chunk-fold radius. 0 = off, 1 = 3x3 sections (9), 2 = 5x5 (25),
 *                   3 = 7x7 (49). Bigger = fewer calls but a longer stall when it lands.
 */
public final class NpuConfig {

    public boolean enabled = true;
    public boolean autoWarmup = true;
    public boolean debugLog = false;

    /** Run the full diagnostic set by itself once the world is up. */
    public boolean autoProbe = true;

    /**
     * Also run the NPU pass over sky light.
     *
     * Sky light is the same shape of work as block light, so it rides the same
     * path. Off by default because its propagation rule is not the same one the
     * linearised operator models - it does not attenuate on the way down until
     * something opaque blocks it - so the result there is an approximation.
     * Write-back is raise-only either way, so the world cannot get darker.
     */
    public boolean skyLight = false;
    /** Back off automatically when the NPU stops paying for itself. */
    public boolean guardEnabled = true;
    public int lightBatch = 128;
    public int lightFoldRadius = 1;

    /** vanilla | npu | assist */
    /** Proven no-op on a converged BFS light field (bad=0, written=0). Off unless asked for. */
    public String lightMode = "vanilla";
    /** vanilla | npu | assist */
    public String chunkMode = "assist";

    /** Canonical three-way modes. */
    public static final String[] MODES = {"vanilla", "npu", "assist"};

    /**
     * Frozen mode per world seed, so a world is generated by exactly one path from start to
     * finish. See NpuTerrainLock. Keyed by seed; values are one of MODES.
     */
    public final java.util.Map<Long, String> worldLocks =
            new java.util.concurrent.ConcurrentHashMap<>();

    /** Advances a mode field vanilla -> npu -> assist -> vanilla. */
    public static String nextMode(String cur) {
        for (int i = 0; i < MODES.length; i++) if (MODES[i].equalsIgnoreCase(cur)) return MODES[(i + 1) % MODES.length];
        return MODES[0];
    }

    public static String modeLabel(String m) {
        if ("npu".equalsIgnoreCase(m)) return "NPU 接管";
        if ("assist".equalsIgnoreCase(m)) return "NPU 辅助";
        return "原版";
    }

    private static NpuConfig INSTANCE;

    public static synchronized NpuConfig get() {
        if (INSTANCE == null) { INSTANCE = new NpuConfig(); INSTANCE.load(); }
        return INSTANCE;
    }

    private static Path file() {
        return FabricLoader.getInstance().getConfigDir().resolve("mcjavanpu.properties");
    }

    public synchronized void load() {
        try {
            Path p = file();
            if (!Files.exists(p)) { save(); return; }
            Properties pr = new Properties();
            try (var in = Files.newInputStream(p)) { pr.load(in); }
            enabled = Boolean.parseBoolean(pr.getProperty("enabled", "true"));
            autoWarmup = Boolean.parseBoolean(pr.getProperty("autoWarmup", "true"));
            debugLog = Boolean.parseBoolean(pr.getProperty("debugLog", "false"));
            autoProbe = Boolean.parseBoolean(pr.getProperty("autoProbe", "true"));
            skyLight = Boolean.parseBoolean(pr.getProperty("skyLight", "false"));
            guardEnabled = Boolean.parseBoolean(pr.getProperty("guardEnabled", "true"));
            lightBatch = Integer.parseInt(pr.getProperty("lightBatch", "128"));
            lightFoldRadius = Integer.parseInt(pr.getProperty("lightFoldRadius", "1"));
            // A radius of 3+ folds 49+ sections into one submit and can overrun the single
            // threaded service (observed as SocketTimeoutException on every later request).
            // 2 (5x5 = 25 sections) is the largest batch that stays comfortably inside the
            // IPC payload cap, so clamp here rather than trusting a hand-edited file.
            lightFoldRadius = Math.max(0, Math.min(2, lightFoldRadius));
            // Default is vanilla, and that is a deliberate decision rather than a
            // cautious one. The light path was measured end to end: bad=0/65536
            // (the NPU reproduces the CPU reference exactly) together with
            // written=0 (nothing was ever brighter than vanilla). A linear
            // smoothing operator over an already-converged BFS light field cannot
            // produce a higher value, so this path cannot do useful work. Leaving
            // it on by default would only cost 10-38ms per call during chunk
            // loading. It stays selectable for anyone who wants to keep measuring.
            lightMode = pr.getProperty("lightMode", "vanilla");
            chunkMode = pr.getProperty("chunkMode", "assist");
            for (String k : pr.stringPropertyNames()) {
                if (!k.startsWith("worldLock.")) continue;
                try {
                    long s = Long.parseLong(k.substring("worldLock.".length()));
                    String m = pr.getProperty(k);
                    if (NpuTerrainLock.isMode(m)) worldLocks.put(s, m.toLowerCase(java.util.Locale.ROOT));
                } catch (NumberFormatException ignored) {
                    // A malformed key is not worth failing a load over.
                }
            }
            NpuLog.log("config loaded from " + p);
        } catch (Throwable t) {
            NpuLog.error("config load failed, using defaults", t);
        }
    }

    public synchronized void save() {
        try {
            Properties pr = new Properties();
            pr.setProperty("enabled", String.valueOf(enabled));
            pr.setProperty("autoWarmup", String.valueOf(autoWarmup));
            pr.setProperty("debugLog", String.valueOf(debugLog));
            pr.setProperty("autoProbe", String.valueOf(autoProbe));
            pr.setProperty("skyLight", String.valueOf(skyLight));
            pr.setProperty("guardEnabled", String.valueOf(guardEnabled));
            pr.setProperty("lightBatch", String.valueOf(lightBatch));
            pr.setProperty("lightFoldRadius", String.valueOf(lightFoldRadius));
            pr.setProperty("lightMode", lightMode);
            pr.setProperty("chunkMode", chunkMode);
            for (java.util.Map.Entry<Long, String> e : worldLocks.entrySet()) {
                if (e.getValue() != null) pr.setProperty("worldLock." + e.getKey(), e.getValue());
            }
            Path p = file();
            Files.createDirectories(p.getParent());
            try (var out = Files.newOutputStream(p)) {
                pr.store(out, "MCJavaNPU switches");
            }
            NpuLog.log("config saved to " + p);
        } catch (Throwable t) {
            NpuLog.error("config save failed", t);
        }
    }

    public synchronized void toggle(String key) {
        switch (key) {
            case "enabled": enabled = !enabled; break;
            case "autoWarmup": autoWarmup = !autoWarmup; break;
            case "debugLog": debugLog = !debugLog; break;
            case "autoProbe": autoProbe = !autoProbe; break;
            case "skyLight": skyLight = !skyLight; break;
            case "guardEnabled": guardEnabled = !guardEnabled; break;
            case "lightFoldRadius": lightFoldRadius = (lightFoldRadius + 1) % 5; break;
            case "lightMode": lightMode = nextMode(lightMode); break;
            case "chunkMode": chunkMode = nextMode(chunkMode); break;
            default: return;
        }
        save();
        NpuLog.log("config toggled " + key + " -> " + describe());
    }

    public String describe() {
        return "enabled=" + enabled + " autoWarmup=" + autoWarmup
                + " debugLog=" + debugLog + " autoProbe=" + autoProbe
                + " skyLight=" + skyLight
                + " guardEnabled=" + guardEnabled
                + " lightBatch=" + lightBatch
                + " lightFoldRadius=" + lightFoldRadius
                + " lightMode=" + lightMode + " chunkMode=" + chunkMode;
    }
}
